#a=(1,2,3,4,2,5,1,9,1)
set_smple = set()
print(type(set_smple))
print(set_smple)
set_smple.add(0)
set_smple.add(1)
set_smple.add(2)
s1 = set_smple.union({2,3,4})
s2= ({4,5,6})
intersection = set_smple.difference(s2)
print(set_smple, s1, intersection)